import type { AppState } from '../types';
import { generateTutorNarrative, formatSprintDate, humanize } from '../reports/tutor-narrative';
import { thisWeek, flaggedAttempts, misconceptionStruggles } from '../analytics/tagging';
import { MathText } from './katex';

export type TutorReportProps = {
  appState: AppState;
  asOfMs: number;
  onBackDashboard: () => void;
};

export function TutorReport({ appState, asOfMs, onBackDashboard }: TutorReportProps) {
  const narrative = generateTutorNarrative(appState, asOfMs);
  const weekSprints = thisWeek(appState.sprints, asOfMs);
  const flagged = flaggedAttempts(weekSprints);
  const misconceptions = misconceptionStruggles(weekSprints);

  return (
    <main class="report-page">
      <nav class="report-nav no-print">
        <button class="link-btn" onClick={onBackDashboard}>
          ← Dashboard
        </button>
        <button class="primary-btn" onClick={() => window.print()}>
          Print or save as PDF
        </button>
      </nav>

      <header class="report-header">
        <h1>Tutor briefing — Beatrix</h1>
        <p class="report-week">{narrative.weekLabel}</p>
      </header>

      <section class="report-tidy">{narrative.tidyModeNote}</section>

      <section class="report-narrative">
        {narrative.sentences.map((s, i) => (
          <p key={i}>{s}</p>
        ))}
      </section>

      {misconceptions.length > 0 && (
        <section class="report-section">
          <h2>Mistake patterns this week</h2>
          <ul>
            {misconceptions.map((m) => (
              <li key={m.tag}>
                <strong>{m.count}×</strong> {humanize(m.tag)}
              </li>
            ))}
          </ul>
        </section>
      )}

      {flagged.length > 0 && (
        <section class="report-section">
          <h2>Flagged for help</h2>
          <ol class="flagged-detail-list">
            {flagged.map((a) => (
              <li key={`${a.problemId}-${a.startedAt}`}>
                <div class="flagged-problem">
                  <MathText text={a.problem.text} />
                </div>
                <div class="flagged-meta">
                  She entered <code>{a.enteredFirst}</code> first, then <code>{a.enteredRetry}</code>.
                  Correct answer: <strong>{a.problem.answer.canonical}</strong>.
                  {a.misconception && (
                    <span>
                      {' '}— pattern: <em>{humanize(a.misconception)}</em>.
                    </span>
                  )}
                </div>
              </li>
            ))}
          </ol>
        </section>
      )}

      {weekSprints.length > 0 && (
        <section class="report-section">
          <h2>Sprints this week</h2>
          <ul class="sprint-quick-list">
            {weekSprints.map((s) => {
              const correct = s.attempts.filter((a) => a.result === 'correct').length;
              return (
                <li key={s.id}>
                  {formatSprintDate(s)} — {correct}/{s.attempts.length} on first try
                </li>
              );
            })}
          </ul>
        </section>
      )}

      <footer class="report-footer">
        <p class="footer-note">
          DRAFT — requires human review. Generated by the Math Engine.
        </p>
      </footer>
    </main>
  );
}
